"""Context packet generated by the PCLTM injection arbitrator."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping, Sequence

from .budget_manager import BudgetAllocation
from .candidate import INJECTION_PRIORITY, CandidateType, InjectionCandidate
from .conflict_filter import ConflictDecision


SECTION_TITLES: Mapping[CandidateType, str] = {
    CandidateType.SYSTEM: "System / Safety / Tool Discipline",
    CandidateType.CORE_IDENTITY: "Core SOUL Identity Anchor",
    CandidateType.RUNTIME_MODE: "Runtime Mode Layer",
    CandidateType.ACTIVE_DIALOGUE: "Active Dialogue State",
    CandidateType.CURRENT_TASK: "Current Task State",
    CandidateType.PERSONA_EMOTION: "Emotional / Persona State",
    CandidateType.SESSION_SPINE: "Session Summary Spine",
    CandidateType.EPISODIC_MEMORY: "Relevant Episodic Memories (events)",
    CandidateType.SEMANTIC_MEMORY: "Relevant Semantic Memories (sourced facts)",
    CandidateType.PROCEDURAL_SKILL: "Procedural Skills",
    CandidateType.BACKGROUND_CONTEXT: "Optional Background Context",
}


@dataclass(frozen=True)
class InjectionAudit:
    injected: Sequence[dict[str, object]]
    rejected: Sequence[dict[str, object]]
    conflict_decisions: Sequence[dict[str, object]]
    budget: dict[str, object]

    def to_dict(self) -> dict[str, object]:
        return {
            "injected": list(self.injected),
            "rejected": list(self.rejected),
            "conflict_decisions": list(self.conflict_decisions),
            "budget": dict(self.budget),
        }


@dataclass(frozen=True)
class ContextPacket:
    """Final, explainable packet promoted into a model turn."""

    sections: Mapping[CandidateType, tuple[InjectionCandidate, ...]]
    audit: InjectionAudit
    total_tokens: int
    metadata: Mapping[str, object] = field(default_factory=dict)

    def render(self) -> str:
        lines: list[str] = []
        for candidate_type in sorted(self.sections, key=lambda item: INJECTION_PRIORITY[item]):
            candidates = self.sections[candidate_type]
            if not candidates:
                continue
            lines.append(f"## {SECTION_TITLES[candidate_type]}")
            for candidate in candidates:
                label = _candidate_label(candidate)
                lines.append(f"- [{label}] {candidate.content.strip()}")
            lines.append("")
        return "\n".join(lines).strip()

    def to_dict(self) -> dict[str, object]:
        return {
            "sections": {
                candidate_type.value: [candidate.to_audit_dict() for candidate in candidates]
                for candidate_type, candidates in self.sections.items()
            },
            "audit": self.audit.to_dict(),
            "total_tokens": self.total_tokens,
            "metadata": dict(self.metadata),
            "rendered": self.render(),
        }


def build_context_packet(
    selected: Sequence[InjectionCandidate],
    *,
    rejected: Sequence[tuple[InjectionCandidate, str]],
    conflict_decisions: Sequence[ConflictDecision],
    budget: BudgetAllocation,
    metadata: Mapping[str, object] | None = None,
) -> ContextPacket:
    sections: dict[CandidateType, list[InjectionCandidate]] = {}
    for candidate in sorted(selected, key=lambda item: (item.priority, item.key)):
        sections.setdefault(candidate.type, []).append(candidate)

    frozen_sections = {key: tuple(value) for key, value in sections.items()}
    injected_audit = [
        {
            **candidate.to_audit_dict(),
            "reason": "selected-within-fixed-layer-budget",
        }
        for candidate in selected
    ]
    rejected_audit = [
        {
            **candidate.to_audit_dict(),
            "reason": reason,
        }
        for candidate, reason in rejected
    ]
    audit = InjectionAudit(
        injected=injected_audit,
        rejected=rejected_audit,
        conflict_decisions=[decision.to_dict() for decision in conflict_decisions],
        budget=budget.to_dict(),
    )
    return ContextPacket(
        sections=frozen_sections,
        audit=audit,
        total_tokens=sum(candidate.token_cost or 0 for candidate in selected),
        metadata=dict(metadata or {}),
    )


def _candidate_label(candidate: InjectionCandidate) -> str:
    if candidate.type is CandidateType.EPISODIC_MEMORY:
        return f"event:{candidate.key}"
    if candidate.type is CandidateType.SEMANTIC_MEMORY:
        confidence = "unknown" if candidate.confidence is None else f"{candidate.confidence:.2f}"
        return f"fact:{candidate.key}; source={candidate.source}; confidence={confidence}"
    if candidate.type is CandidateType.PROCEDURAL_SKILL:
        return f"skill:{candidate.key}"
    return candidate.key
